apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cdg9u4ljm-nodejs
  janus-idp.io/tekton: cdg9u4ljm-nodejs
  backstage.io/kubernetes-id: cdg9u4ljm-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cdg9u4ljm-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
