apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cdg9u4ljm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cdg9u4ljm-nodejs 
  name: cdg9u4ljm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cdg9u4ljm-nodejs 
